import PageTitle from "@/components/PageTitle";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function Layout({children}) {
   return (
      <>
         <PageTitle
            pageTitle='ПОДАТИ ЗАЯВКУ'
            pagesub='Подати заявку'
         />
         {children}
      </>
   );
}
